### PR TITLE
Preparing for new version of lmerTest

### PR DESCRIPTION
**Pull request by runehaubo**
Hello,

When preparing an update of lmerTest we noticed that simr doesn't pass its checks with the new lmerTest. Please consider this pull request which makes simr work with both current/cran version as well as the upcoming version of lmerTest.

The new version of lmerTest is at https://github.com/runehaubo/lmerTestR. For further information about the new version of lmerTest, please see https://github.com/runehaubo/lmerTestR/blob/master/pkg_notes/new_lmerTest.pdf

Release plans for the new lmerTest are still a bit sketchy as other packages need updates as well, but I wanted to share this PR with you after having played around with simr+lmerTest.

Cheers
Rune
for the lmerTest developers

### CODE REVIEW

**Comment by pitakakariki** [comment]
Thanks.

Will there be another warning before the new version gets released? I need to tidy up the github version of simr before I push anything to cran, may be a little while before I find the time.

On the other hand I don't want to be the one holding up release so if it gets close to release date I'll expedite the process somehow.

**Comment by runehaubo** [comment]
Don't worry: I expect 2-3 weeks before we are in place to push lmerTest to CRAN. And we we will reach out before then as well.

Thanks for the quick response.

**Comment by pitakakariki** [comment]
Sorry if you got a bunch of notifications on this, just tidying up.

**Comment by pitakakariki** [comment]
bump

**Pull request merged**
