### PR TITLE
Parallel

### PR DESCRIPTION
**Pull request by palday**
parallel support now built into the `maybe_llply()` call.

### CODE REVIEW

**Comment by pitakakariki** [comment]
See if close & reopen will rerun checks (and include appveyor checks).

**Comment by palday** [comment]
Looks like it will. :) Also, I think even an empty push will do that.

The problem in the new checks seems to be a subtle dependency issue:

```
* checking package dependencies ... ERROR
Package suggested but not available: 'doMC'
 
The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.
```

I think`doMC` isn't available because it lacks Windows support and thus has no Windows binaries on CRAN. 

The parallel test suite uses the `doParallel` backend anyway, as appears to have better cross platform availability. In terms of whether `doParallel` and `doMC`, there's little practical difference from a user perspective in setting up a parallel run: `registerDoParallel(cores=n)` vs `registerDoMC(cores=n)`. Both are supported because `plyr` supports both.

Looking at [`plyr`'s CRAN page](https://cran.r-project.org/web/packages/plyr/index.html), we could follow their example and support `doMC` but leave it off the suggests list.

**Comment by pitakakariki** [comment]
It might be a little trickier than that. In Linux you can use "fork" type parallel execution. On Windows it appears the only option is the "snow" type: [see e.g. this explanation on SO](http://stackoverflow.com/questions/17196261/understanding-the-differences-between-mclapply-and-parlapply-in-r).

The "snow" type also has the advantage that you can extend it to multiple machines, but you have to mess around with exporting too.

**Comment by palday** [comment]
Right, but all of that magic is handled by the interfaces to the `do*` backends (and documented there): `plyr` internally uses `foreach` which in turn can use any of the `do*` packages. Since `simr` uses a call to `llply()`, we can let `plyr` handle the issue of which function exact call is necessary. I haven't yet tested the "snow" backend (but will do so as soon as a currently running calculation has finished), but it looks like the extra setup with `doParallel` is only mildly tedious:

**snow:**
```R
library(doParallel)
cl <- makePSOCKcluster(2)
registerDoParallel(cl)
powerSim(fm1,nsim=10,seed=42,parallel=TRUE)
stopCluster(cl)
```

**fork:**
```R
library(doParallel)
registerDoParallel(cores=2)
powerSim(fm1,nsim=10,seed=42,parallel=TRUE)
```
For the snow/non-shared memory case, we might have to be slightly more careful with exporting the `fit` and `sim` dataframes, but that's also an easy fix with `.paropts=` option in `llply()`. Still it's probably a good idea to add the above block as a test, so I'll do that and remove the `doMC` parallelism.

PS: Another great guide on parallel issues in R can be found [here](http://www.glennklockwood.com/data-intensive/r/parallel-options.html).

**Comment by palday** [comment]
I'm not sure why these tests are failing -- I've tested them on Windows, Linux and OS X without issue when running "test all", but when running "check" (`R CMD CHECK`), it hangs.

**Pull request merged**
